\clearpage

# Discussion

In this report, we summarized the available data collected from commercial fishing vessels by at-sea observers from 1996 to 2021 for 29 groundfish species that are found off the coast of British Columbia. We presented the data for each species over 3 pages. The first page summarized the amounts and types of data that we have for that species (i.e., for any given year or area, the number of individual specimens for which we have length, weight, maturity, or age data, and over how many fishing events that data was collected). Page two displayed the commercial catch and commercial specimen amounts for each year and area. It also included a figure showing how representative the commercial specimens are compared to the catch (e.g., were all of the specimens collected during one time of the year or spread out evenly across space and time?). The third page plotted the age and length frequency data, separated by sex, for each year and area.

Of the 29 species included in this report, Pacific Hake (*Merluccius productus*)  had the best data coverage over time and space. Pacific Hake is only missing two years of sorted specimen data, otherwise every year and area contains at least some, if not abundant, data. No species had complete data coverage (i.e., data from every year in every area). Pacific Ocean Perch (*Sebastes alutus*) also has near complete data coverage; however, like most species, it does not have any data from Area 4B. A number of other species have good data coverage over space and time, such as Arrowtooth Flounder (*Atheresthes stomias*) and Yellowtail Rockfish (*Sebastes flavidus*). Some species had very consistent data across space and time, but the data was almost exclusively from sorted specimens (e.g., Pacific Halibut, *Hippoglossus stenolepis*), or unsorted specimens (e.g., Sablefish, *Anoplopoma fimbria*). 

Longnose Skate (*Raja rhina*) and Shortracker Rockfish (*Sebastes borealis*) were the two most poorly sampled species, with only 7 or 8 fishing event’s worth of data covering only 4 or 3 areas over the 26-year period, respectively. Big Skate (*Beringraja binoculata*) and Yelloweye (*Sebastes ruberrimus*) were also poorly sampled. 

Overall, of the species included in this report, most species stopped being sampled in 2019-2020 due to the COVID-19 pandemic. However, we stopped receiving unsorted data for many species before this time. On average, Flatfish ended unsorted sampling in 2015, and sorted sampling in 2017-2019. Most Rockfish continued to be sampled until 2020, yet some species stopped unsorted sampling earlier (e.g., 2018 or earlier). Round fish, such as Pacific Hake and Pacific Cod (*Gadus macrocephalus*), have the most consistent coverage of data across time. Some species, such as Lingcod (*Ophiodon elongatus*) and Yelloweye, have large gaps in data or stopped receiving data much earlier, likely due to changes in policy. For example, we only received unsorted data for Lingcod since 2013 and only in Area 4B, while sorted data collection ended completely in 2010 and never occurred in Area 4B. Many species also exhibited a gap in sorted specimen collection somewhere in the late 2000’s and early 2010’s, lasting 1-7 years. If this gap occurred, usually unsorted specimen collection would increase to fill it. 

Overall, for most species, there was very poor data collection in Area 4B  and the best specimen collection occurred pre-2005.  Often for rockfish, the line on the length frequency plot that summarizes sexed and unsexed data is skewed to the right, likely because rockfish can be difficult to sex when they are small. It was common for the collected specimens of an area-year combination to be poorly representative of the catch, but that the samples are representative across time when averaged over all areas.  

There is a discrepancy between what data is collected and what data could be and is actually used in stock assessments or other studies. Data from sorted specimens are not used in stock assessments; however,  data from unsorted specimens is becoming less common over time. In addition, age structures are often collected, yet very few of them are analyzed for their age. On average, fewer than half of the collected age structures are analyzed. 

\clearpage
