\clearpage

# Results {#sec:synopsis-plots}

This section contains the species-by-species data visualizations. 
Each species is shown on four pages with similar layout used throughout. 
See Section \@ref(sec:plot-descriptions) for detailed figure captions, including information on interpretation of the figures. 
In addition to the figures, we also provide the scientific name, taxonomic details, DFO species code [commonly the page number in @hart1988], a link to the FishBase and WoRMS (World Register of Marine Species) web pages, details of the most recent DFO Research Documents and Science Advisory Reports, and information or publications related to designations by the COSEWIC^[Committee on the Status of Endangered Wildlife in Canada] and listings under the SARA^[*Species at Risk Act*] (if applicable). 
We also provide a short narrative of the major trends apparent for each species.
The species are ordered according to DFO species codes. 
Section \@ref(sec:common-name-index) provides links to the pages sorted alphabetically by common name. 

\clearpage

<!-- \afterpage{\null\newpage} -->
