\clearpage

# Discussion {#sec:discussion}

In this report, we summarized the available data collected from commercial fishing vessels by At-Sea Observers and Dockside Samplers from 1996 to 2022 for 29 groundfish species found in British Columbia. We presented the data for each species over four pages. The first page displayed the commercial catch and specimen collection for each year and area. The second page summarized the type and quantity of data collected for that species. The third page qualitatively showed how representative the specimen collections were compared to the catch. The fourth page plotted the age (unsorted and sorted specimens) and length frequency (unsorted specimens only) data, separated by sex, for each year and PMFC area.

Of the 29 species included in this report, Pacific Hake had the most complete data coverage over time and space. Unsorted specimens of Pacific Hake were collected every year, and sorted specimen data were only lacking from 2014 and 2015. Every area contained at least some, if not abundant, data. Pacific Ocean Perch and Sablefish also had near complete data coverage of unsorted specimens. Other species that had strong data coverage were Arrowtooth Flounder and Yellowtail Rockfish. Pacific Halibut had consistent data across space and time, but the data were almost exclusively from sorted specimens.

Longnose Skate and Shortraker Rockfish were the two most poorly sampled species in this report, with only seven or eight sampling events in only four or three areas over the 27 years, respectively. Big Skate and Yelloweye Rockfish were also poorly sampled. Yelloweye Rockfish were primarily caught by the hook-and-line fleet, where biological sampling programs to complement Electronic Monitoring have not yet been developed. Most commercial samples of Yelloweye Rockfish that do exist are a result of special projects undertaken jointly by DFO Science and the fishing industry.

Due to the COVID-19 pandemic, the ASOP was suspended in 2020, which stopped sampling for most species included in this report. However, unsorted data collection stopped before 2019 for many species. On average, unsorted flatfish sampling ended in 2015, and sorted sampling ended between 2017 and 2019. Unsorted rockfish sampling stopped in 2018 or earlier for some species, while most rockfish continued sorted sampling until 2020. Many species also exhibited a gap in sorted specimen collection in the late 2000s to early 2010s, lasting 1--7 years. If this gap occurred, the collection of unsorted specimens usually increased during that time. However, the shift in specimen classification could be the result of a change of protocol or in how the specimens were coded in the database.

The number of specimens collected in a year was typically related to the magnitude of the catch of that year. Most species had little to no biological data collected in Area 4B, but these species were either not found or had fishing closures in the Strait of Georgia. If these species did have a small amount of catch or specimens collected in Area 4B, they usually came from minor areas 12 (Queen Charlotte Strait) and 20 (Juan de Fuca Strait) (Figure \@ref(fig:minor-area-map)). The few species with a high quantity of catch and specimens collected from Area 4B were Pacific Hake, Pacific Spiny Dogfish, Quillback Rockfish, and Walleye Pollock. These species were caught and sampled throughout Area 4B. English Sole were historically caught in high quantities throughout Area 4B, but since 1996, only one sample has been collected, and it was in minor area 12. In addition, for most species, the best specimen collection across all areas occurred pre-2005, likely by dockside sampling. In the case of rockfishes, this trend could be linked to the reduction, by up to 75%, in the total allowable catch (TAC) for some inshore between 2002 and 2005 [@davis_evaluating_2008]. Similarly, representativeness tended to be higher when more samples were collected. Often, if sampling was not representative at the area level, it was representative when totalled across all areas.

Only two species had commercial samples collected between the suspension of the ASOP in 2020 and 2022: Pacific Hake and Sablefish. AMR port samplers collected Pacific Hake samples from the landed catch of electronically monitored shoreside trips [@grandin2024hake]. Pacific Hake samples were not collected from freezer trawlers between 2020-2021; however, in 2022, samples were collected by fishing crew from two tows per trip and delivered to AMR port samplers as frozen specimens [@grandin2024hake]. Sablefish were sampled by a voluntary head-only sampling program [@haist2001sablefish; @lacko2023sablefish_head]. In the head-only sampling program, which started in 2018, specimens are processed at sea with a “J-cut” to remove the head, examined to determine sex, marked with standardized knife cuts on the operculum to indicate sex, and stored frozen for later sampling [@lacko2023sablefish_head]. On shore, the frozen head samples are measured for interorbital distance, which can be converted to fork length, and dissected for otoliths for future ageing [@lacko2023sablefish_head].

Weight data from individual fish are important in some stock assessments, such as Pacific Cod and Walleye Pollock, which rely heavily on commercial mean-weight indices; however, weight data were lacking for many species. Weights are challenging to measure at sea because scales generally rely on an immobile base to infer mass from the force imposed by gravity. At sea, additional forces due to ship motion often frustrate accurate weight measurement. Where weights were collected, they were generally measured on shore (dockside) from sorted specimens between 2000 and 2010. Surprisingly, sexed length data were also often missing for species easily sexed externally (i.e., sharks and skates).

Throughout the process of assembling this report, we discovered several issues and challenges with classifying specimens as unsorted or sorted and determining whether a specimen was sampled at sea or dockside. These issues require further investigation outside of this report. The Pacific Halibut data highlight a challenge with classifying specimens as unsorted or sorted. Pacific Halibut are not permitted for retention by trawl gear regardless of size, so all specimens are measured for quota management and then discarded. Since they are discarded, the current system classifies them as sorted. However, since *all* specimens are discarded, the sample is unbiased and would be a “total catch” sample, so the specimens could be considered unsorted. An additional issue with classifying specimens as unsorted or sorted is the unsorted specimens with weight measurements. The ASOP did not have scales at sea; however, it is unlikely that any specimens sampled dockside were truly unsorted. Those specimens may be unsorted by species, but unless 100% retention was required, small unmarketable fish were often discarded at sea. Unsorted specimens with weights may just be an issue with how they were coded at the time. Another challenge we faced was discerning specimens sampled at sea vs. dockside. There is no one column that indicates whether a specimen was sampled at sea or dockside.

Stock assessment and research data needs continue to change as data analysis methods and fishery patterns change. Sorted specimen data that were adequate for earlier assessment models have been used less in recent years, while the need for unsorted specimens, especially ageing data, to condition integrated age-structured models has grown. Despite the common need for ageing data, fewer than half the collected commercial age structures have been analyzed on average. Specimens with an associated latitude and longitude are also increasingly needed to standardize composition data in space and time [@thorson2024spatiotemporal; @anderson2024sdmtmb]. These data can also be used for research investigating variation in body size, condition, and growth [e.g., @frid2016spatial; @lindmark2023spatiotemporal]. Despite a continued need for unsorted specimen data that preserves the latitude and longitude of catch, commercial specimen collection declined markedly between the early 2000s and the beginning of the COVID-19 pandemic in 2020, from which it has yet to recover. This report summarized the commercial biological sampling data for 29 groundfish species over 27 years, including data types and trends. We hope this information helps inform future commercial sampling decisions for groundfish in British Columbia.

\clearpage

