---
title: |
  "A review of biological samples collected from commercial groundfish fisheries in British Columbia, 1996--2022"
french_title: | 
  "Titre ici (*Nom latin de l'espèce*)"
year: 2024
report_number: nnn
author: |
  Leah. C. Walker^1^,
  Luke A. Rogers^1^,
  Sean C. Anderson^1^, and
  Dana R. Haggarty^1^
author_list: "Walker, L.C., Rogers, L.A., Anderson, S.C., and Haggarty D.R."
region: Pacific Region
french_region: Région du Pacifique
isbn: ""
citation_french: "Last, F.M. et Smith, A.B. Title Here (*Latin Species Name*). DFO Secr. can. des avis sci. du MPO. Doc. de rech 2019/nnn. iv + 13 p."
address: |
  ^1^Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
french_address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190 Hammond Bay Road\
     Nanaimo, Colombie-Britannique, V9T 6N7, Canada\
  \smallskip
  ^2^Loin, très loin\
     Une autre galaxie
phone: "(555) 555-5555"
author_footnote: "Email: Leah.Walker@dfo-mpo.gc.ca | telephone: (250) 756-5555"
abstract: |
 Biological data collected from commercial fishing catches are an important component of fisheries stock assessments. In Canada's Pacific Region, these data have been collected by the At-Sea Observer Program (ASOP), dockside sampling programs, and special projects. However, during the COVID-19 pandemic, the ASOP was paused, and it has not been reintroduced, profoundly affecting the type and quantity of data collected from commercial fishing catches. This report was developed to provide an overview of data collection and availability from 1996 to 2022 for major BC groundfish species of commercial and conservation interest. The data were presented at a coastwide scale and also by finer Pacific Marine Fisheries Commission (PMFC) areas so that spatial and temporal trends in British Columbia could be identified. The goals of the report were to (1) summarize available data collected on commercial fishing vessels and (2) represent the temporal and spatial trends of the biological data by groundfish species. This report highlights what data are no longer being collected and can guide decisions on future sampling programs, data collection, and resource allocation.
french_abstract: |
 Les données biologiques recueillies dans les prises de la pêche commerciale constituent un élément important de l’évaluation des stocks de poissons. Dans la région du Pacifique au Canada, ces données ont été recueillies dans le cadre du Programme des observateurs en mer (POM), des programmes de vérification à quai et de projets spéciaux. Cependant, la pandémie de COVID-19 a mené à l’interruption du POM, qui n’a d’ailleurs pas encore été remis en œuvre, ce qui a pour effet d’affecter de manière importante le type et la quantité de données recueillies dans les prises de la pêche commerciale. Ce rapport a été rédigé dans le but de donner un aperçu de la cueillette et de la disponibilité des données de 1996 à 2022 pour les principales espèces de poissons de fond d’intérêt sur le plan commercial et sur le plan de la conservation en Colombie-Britannique. On a présenté les données à l’échelle de la côte et par zones de la Commission des pêches maritimes du Pacifique (CPMP) à plus petite échelle afin de déterminer les tendances spatiales et temporelles en Colombie-Britannique. Les objectifs du rapport étaient de 1) résumer les données disponibles recueillies sur les navires de pêche commerciale et 2) représenter les tendances temporelles et spatiales des données biologiques par espèce de poisson de fond. Ce rapport met en évidence les données qui ne sont plus recueillies et peut aider à orienter les décisions relatives aux futurs programmes de surveillance, à la cueillette de données et à l’affectation des ressources.

output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: true
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
   draft_watermark: false
   highlight: tango
type:
  techreport
# ------------
# End of options to set
knit: (function(input, ...) {
       csasdown::render('_bookdown.yml')
      })
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float}
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos,
  optipng = "-strip all"
)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(dplyr)
library(ggplot2)
library(readr)
library(tibble)
library(rosettafish)
library(csasdown)
```
